version: "3.2"

volumes:
  db-maria_data:
  api_node_modules:

services:
  db-maria:
    build:
      context: .
      dockerfile: db-maria.Dockerfile
    ports:
      - 13306:3306
    restart: always
    volumes:
      - db-maria_data:/var/lib/mysql
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 3100:3100
      - 9229:9229
    env_file: .env
    volumes:
      # - ./api:/var/www/html this volume mount cause package.json not found error
      - api_node_modules:/var/www/html/node_modules
    command: bash -c "/wait-for-it.sh db-maria:3306 --strict -- yarn && yarn start"
