version: "3.2"

volumes:
  db-maria_data:
  api_node_modules:

services:
  db-maria:
    build:
      context: .
      dockerfile: db-maria.Dockerfile
    image: hbjs97/pipelinetest-db-maria
    ports:
      - 13307:3306
    restart: always
    volumes:
      - db-maria_data:/var/lib/mysql
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: hbjs97/pipelinetest-api
    ports:
      - 4100:4100
      - 9339:9339
    env_file: .env
    volumes:
      - ./api:/var/www/html
      - api_node_modules:/var/www/html/node_modules
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
